name: Release content snaps

on:
  workflow_dispatch:
    inputs:
      snap:
        description: name of the snap to release
        required: true
        default: all
      upload:
        description: upload snap to snap store
        required: true
        default: false

jobs:
    prepare:
      runs-on: [self-hosted, large, jammy, X64]
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v4
          with:
              distribution: 'temurin'
              java-version: '21'
              cache: 'maven'
        - run: |
            set -ex
            sudo apt-get update && sudo apt-get install -y make maven openjdk-21-jdk-headless
            make prepare
            if [ ${{ github.event.inputs.snap }} -eq "all" ]; then
              snaps_json = $(yq eval -o=json devpack-for-spring-manifest/supported.yaml | jq ".\"content-snaps\" | keys")
            else
              snaps_json = $( echo "[ \"${{ github.event.inputs.snap }}\"]")
            fi
            echo "matrix=$(echo $snaps_json)" >> $GITHUB_OUTPUT


    build_content:
      needs: prepare
      runs-on: [self-hosted, large, jammy, X64]
      strategy:
        matrix:
          snap: ${{fromJson(needs.prepare.outputs.matrix)}}
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v4
          with:
              distribution: 'temurin'
              java-version: '21'
              cache: 'maven'
        - run: |
            sudo apt-get update && sudo apt-get install -y make maven openjdk-21-jdk-headless
            make prepare
        - name: Build ${{matrix.snap}}
          id: build
          uses: snapcore/action-build@v1
          with:
            path: target/${{matrix.snap}}
        - name: Upload Snap to workflow artifacts
          id: upload-artifact
          uses: actions/upload-artifact@v4
          with:
            name: ${{matrix.snap}}
            path: ${{ steps.build.outputs.snap }}
